-- DATE_FORMAT(컬럼, 포맷) : DATE FORMAT 변경
-- IN() : OR와 같은 역할, 하나 이상 일치하면 TRUE
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD IN("CS", "GS")
ORDER BY HIRE_YMD DESC, DR_NAME ASC;